### ISSUE TITLE
Doesn't push my links on Twitter

### ISSUE THREAD

**Issue by f0x2501** [ArthurHoaro/shaarli2twitter#2]
Hi ArthurHoaro,
do you know how to debug because I follow your install documentation, fill right the form and nothing is push to my twitter account. I try to regenerate tokens, nothing.
My php version 5.6 , curl present and my shaarli version is 0.8.
Thank !

**Comment by f0x2501** [comment]
Sorry, it was my theme who hide the twitter checkbox. Maybe you could update your readme to explain the need to check the twitter checkbox before sending a new link to your shaarli.
Thank !

**Comment by ArthurHoaro** [comment]
Hi!

Yes I can, however your theme is supposed to contain plugin hooks. Which one are you using?

**Comment by f0x2501** [comment]
![screenshot-20161212-20 09 23](https://cloud.githubusercontent.com/assets/284631/21112803/6aee1aa0-c0a7-11e6-8686-ce3092e17572.png)
http://f.0x2501.org/s/
I use a crappy homemade theme who need some css fixes.
