### ISSUE TITLE
Can't save links with shaarli2twitter activated

### ISSUE THREAD

**Issue by grolimur** [ArthurHoaro/shaarli2twitter#3]
Hi,
I get the following errors when I try to save a link with shaarli2twitter activated:

**Notice**: Undefined variable: conf in **/home/clients/39444dbe3915f55f85721e58093ddc6b/web/shaarli/plugins/shaarli2twitter/shaarli2twitter.php** on line **115**

**Fatal error**: Call to a member function get() on null in **/home/clients/39444dbe3915f55f85721e58093ddc6b/web/shaarli/plugins/shaarli2twitter/shaarli2twitter.php** on line **276**

Any idea how to deal with that?
Thanks in advance.

**Comment by ArthurHoaro** [comment]
I don't really see any reason for `$conf` to be null. Before further debugging, can you make sure that `shaarli_version.php` contains:

    <?php /* 0.8.0 */ ?>

And `application/PluginManager.php#L102` is:

    $data = call_user_func($hookFunction, $data, $this->conf);

Note that your issue doesn't seem directly related to this plugin, but either with Shaarli or Shaarli/plugin compatibility.

**Comment by grolimur** [comment]
Actually, the last stable version was 0.7.0 (`shaarli_version.php` contains `<?php /* 0.7.0 */ ?>`).
I will update my Shaarli instance and try again.
Sorry.

**Comment by ArthurHoaro** [comment]
No problem. Stable branch is usually a digit behind, but you *should* be fine with the latest release.

Note that I've release a new version of Shaarli last night. I also updated this plugin.
EDIT: **warning** - custom themes probably aren't compatible with the latest release yet.
