### ISSUE TITLE
Tweet both URLs

### ISSUE THREAD

**Issue by angristan** [ArthurHoaro/shaarli2twitter#5]
Hi,

Instead of tweeting just the link or just the shaarli link, wouldn't it be better to use tags like `${url}` and `${shaarli_url}` to add the ability to tweet both links ? 

Thanks for the plugin though :)

**Comment by ArthurHoaro** [comment]
Hi @Angristan. While I'm not sure that your use case is super useful, it would remove one setting (`TWITTER_USE_PERMALINK`), which would make the plugin simpler, so ok for this.
