### ISSUE TITLE
Title too shortened

### ISSUE THREAD

**Issue by angristan** [ArthurHoaro/shaarli2twitter#6]
Shaarli : https://links.angristan.xyz/?oDnCKw 
Tweet : https://twitter.com/fuolpit/status/822176523750932480

It only happened tonight, I don't know if it's related to the URL or something else.

**Comment by angristan** [comment]
Doesn't happen here for example : https://twitter.com/fuolpit/status/822194850338631681

**Comment by ArthurHoaro** [comment]
Hmm, yes, I'm not sure how I could miss this. When the tweet length is recalculated, it includes the whole URL instead of the future t.co URL length.
