### ISSUE TITLE
Set new Twitter characters limit

### ISSUE THREAD

**Issue by alexisju** [ArthurHoaro/shaarli2twitter#9]
Since november 2017, Twitter allow to tweet up to 280 characters.
This plugin could be updated to prevent to cut tweet to previous 140-characters limit.

**Comment by ArthurHoaro** [comment]
It should work with [v1.3.1](https://github.com/ArthurHoaro/shaarli2twitter/releases/tag/v1.3.1).

**Comment by alexisju** [comment]
Indeed ;-) Thanks
